### ISSUE TITLE
How do you use it and a more detailed description to c&p

### ISSUE THREAD

**Issue by loginquitas** [XRadius/http-game-apex#1]
Here is something you should add in the description which is a bit more accurate & for brain-dead people with IQ issues.

```
git clone https://github.com/XRadius/http-game-apex
cd http-game-apex
npm install
npm start
```

It still opens the question of how do we pull the server we are in and since it ask for login / password is this for origin only, or can we log in via our Steam accounts? A Video clip of it in action would be on par? ~Koji

**Comment by loginquitas** [comment]
Hi XRadius! Thank you for the quick answer! Hit me up at any time, I am always online 24/7 I am currently working as well on an Apex cheat but it is not working very well haha.

I am gonna test everything out & make a tutorial ^^ ~Koji

**Comment by XRadius** [comment]
I added a ton of details in the README. Do you still miss something? Lemme know 👍
